Plugins/Nop.Plugin.Ecorenew.ElavonHppPayment/Controllers/EcorenewElavonHppPaymentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core;
using Nop.Core.Domain.Logging;
using Nop.Plugin.Ecorenew.ElavonHppPayment.Domain;
using Nop.Plugin.Ecorenew.ElavonHppPayment.Models;
using Nop.Plugin.Ecorenew.ElavonHppPayment.Services;
using Nop.Services.Configuration;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Orders;
using Nop.Services.Stores;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using System;
using System.Linq;

namespace Nop.Plugin.Ecorenew.ElavonHppPayment.Controllers
{
    public class EcorenewElavonHppPaymentController : BasePaymentController
    {
        #region Fields

        private readonly ICurrencyService _currencyService;
        private readonly IEcorenewElavonHppService _elavonHppService;
        private readonly ILocalizationService _localizationService;
        private readonly ILogger _logger;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly IOrderService _orderService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;
        private readonly IStoreService _storeService;
        private readonly IWorkContext _workContext;

        #endregion

        #region Ctor

        public EcorenewElavonHppPaymentController(ICurrencyService currencyService,
            IEcorenewElavonHppService elavonHppService,
            ILocalizationService localizationService,
            ILogger logger,
            IOrderProcessingService orderProcessingService,
            IOrderService orderService,
            ISettingService settingService,
            IStoreContext storeContext,
            IStoreService storeService,
            IWorkContext workContext)
        {
            this._currencyService = currencyService;
            this._elavonHppService = elavonHppService;
            this._localizationService = localizationService;
            this._logger = logger;
            this._orderProcessingService = orderProcessingService;
            this._orderService = orderService;
            this._settingService = settingService;
            this._storeContext = storeContext;
            this._storeService = storeService;
            this._workContext = workContext;
        }

        #endregion

        #region Methods

        /// <summary>
        /// Gets the configuration page for the plugin
        /// </summary>
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public ActionResult Configure()
        {
            // load settings for a chosen store scope
            var storeScope = this.GetActiveStoreScopeConfiguration(_storeService, _workContext);
            var elavonHppPaymentSettings = _settingService.LoadSetting<EcorenewElavonHppPaymentSettings>(storeScope);

            var model = new ConfigurationModel
            {
                UseSandbox = elavonHppPaymentSettings.UseSandbox,
                Account = elavonHppPaymentSettings.Account,
                MerchantId = elavonHppPaymentSettings.MerchantId,
                Secret = elavonHppPaymentSettings.Secret,
                AutoSettle = elavonHppPaymentSettings.AutoSettle,
                HppVersion = elavonHppPaymentSettings.HppVersion,
                HppLanguageCode = elavonHppPaymentSettings.HppLanguageCode,
                DefaultCurrencyCode = elavonHppPaymentSettings.DefaultCurrencyCode,
                UseCustomerCurrency = elavonHppPaymentSettings.UseCustomerCurrency,

                DefaultCurrencySelectList = _currencyService.GetAllCurrencies(storeId: storeScope)
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.CurrencyCode,
                    Selected = x.CurrencyCode == elavonHppPaymentSettings.DefaultCurrencyCode
                }).ToList(),

                ActiveStoreScopeConfiguration = storeScope
            };

            if (storeScope > 0)
            {
                model.UseSandbox_OverrideForStore = _settingService.SettingExists(elavonHppPaymentSettings, x => x.UseSandbox, storeScope);
                model.Account_OverrideForStore = _settingService.SettingExists(elavonHppPaymentSettings, x => x.Account, storeScope);
                model.MerchantId_OverrideForStore = _settingService.SettingExists(elavonHppPaymentSettings, x => x.MerchantId, storeScope);
                model.Secret_OverrideForStore = _settingService.SettingExists(elavonHppPaymentSettings, x => x.Secret, storeScope);
                model.AutoSettle_OverrideForStore = _settingService.SettingExists(elavonHppPaymentSettings, x => x.AutoSettle, storeScope);
                model.HppVersion_OverrideForStore = _settingService.SettingExists(elavonHppPaymentSettings, x => x.HppVersion, storeScope);
                model.HppLanguageCode_OverrideForStore = _settingService.SettingExists(elavonHppPaymentSettings, x => x.HppLanguageCode, storeScope);
                model.DefaultCurrencyCode_OverrideForStore = _settingService.SettingExists(elavonHppPaymentSettings, x => x.DefaultCurrencyCode, storeScope);
                model.UseCustomerCurrency_OverrideForStore = _settingService.SettingExists(elavonHppPaymentSettings, x => x.UseCustomerCurrency, storeScope);
            }

            return View("~/Plugins/Ecorenew.ElavonHppPayment/Views/EcorenewElavonHppPayment/Configure.cshtml", model);
        }

        /// <summary>
        /// Handles the post request for configure
        /// </summary>
        /// <param name="model">The configuration model</param>
        [HttpPost]
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public ActionResult Configure(ConfigurationModel model)
        {
            if (!ModelState.IsValid)
                return Configure();

            //load settings for a chosen store scope
            var storeScope = this.GetActiveStoreScopeConfiguration(_storeService, _workContext);
            var elavonHppPaymentSettings = _settingService.LoadSetting<EcorenewElavonHppPaymentSettings>(storeScope);

            //save settings
            elavonHppPaymentSettings.UseSandbox = model.UseSandbox;
            elavonHppPaymentSettings.Account = model.Account;
            elavonHppPaymentSettings.MerchantId = model.MerchantId;
            elavonHppPaymentSettings.Secret = model.Secret;
            elavonHppPaymentSettings.AutoSettle = model.AutoSettle;
            elavonHppPaymentSettings.HppVersion = model.HppVersion;
            elavonHppPaymentSettings.HppLanguageCode = model.HppLanguageCode;
            elavonHppPaymentSettings.DefaultCurrencyCode = model.DefaultCurrencyCode;
            elavonHppPaymentSettings.UseCustomerCurrency = model.UseCustomerCurrency;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */
            if (model.UseSandbox_OverrideForStore || storeScope == 0)
                _settingService.SaveSetting(elavonHppPaymentSettings, x => x.UseSandbox, storeScope, false);
            else if (storeScope > 0)
                _settingService.DeleteSetting(elavonHppPaymentSettings, x => x.UseSandbox, storeScope);

            if (model.Account_OverrideForStore || storeScope == 0)
                _settingService.SaveSetting(elavonHppPaymentSettings, x => x.Account, storeScope, false);
            else if (storeScope > 0)
                _settingService.DeleteSetting(elavonHppPaymentSettings, x => x.Account, storeScope);

            if (model.MerchantId_OverrideForStore || storeScope == 0)
                _settingService.SaveSetting(elavonHppPaymentSettings, x => x.MerchantId, storeScope, false);
            else if (storeScope > 0)
                _settingService.DeleteSetting(elavonHppPaymentSettings, x => x.MerchantId, storeScope);

            if (model.Secret_OverrideForStore || storeScope == 0)
                _settingService.SaveSetting(elavonHppPaymentSettings, x => x.Secret, storeScope, false);
            else if (storeScope > 0)
                _settingService.DeleteSetting(elavonHppPaymentSettings, x => x.Secret, storeScope);

            if (model.AutoSettle_OverrideForStore || storeScope == 0)
                _settingService.SaveSetting(elavonHppPaymentSettings, x => x.AutoSettle, storeScope, false);
            else if (storeScope > 0)
                _settingService.DeleteSetting(elavonHppPaymentSettings, x => x.AutoSettle, storeScope);

            if (model.HppVersion_OverrideForStore || storeScope == 0)
                _settingService.SaveSetting(elavonHppPaymentSettings, x => x.HppVersion, storeScope, false);
            else if (storeScope > 0)
                _settingService.DeleteSetting(elavonHppPaymentSettings, x => x.HppVersion, storeScope);

            if (model.HppLanguageCode_OverrideForStore || storeScope == 0)
                _settingService.SaveSetting(elavonHppPaymentSettings, x => x.HppLanguageCode, storeScope, false);
            else if (storeScope > 0)
                _settingService.DeleteSetting(elavonHppPaymentSettings, x => x.HppLanguageCode, storeScope);

            if (model.DefaultCurrencyCode_OverrideForStore || storeScope == 0)
                _settingService.SaveSetting(elavonHppPaymentSettings, x => x.DefaultCurrencyCode, storeScope, false);
            else if (storeScope > 0)
                _settingService.DeleteSetting(elavonHppPaymentSettings, x => x.DefaultCurrencyCode, storeScope);

            if (model.UseCustomerCurrency_OverrideForStore || storeScope == 0)
                _settingService.SaveSetting(elavonHppPaymentSettings, x => x.UseCustomerCurrency, storeScope, false);
            else if (storeScope > 0)

Plugins/Nop.Plugin.Ecorenew.ElavonHppPayment/Views/EcorenewElavonHppPayment/Configure.cshtml
@model Nop.Plugin.Ecorenew.ElavonHppPayment.Models.ConfigurationModel
@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="EcorenewElavonHppPayment" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UseSandbox_OverrideForStore" asp-input="UseSandbox" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UseSandbox" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseSandbox" />
                        <span asp-validation-for="UseSandbox"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Account_OverrideForStore" asp-input="Account" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Account" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Account" />
                        <span asp-validation-for="Account"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="MerchantId_OverrideForStore" asp-input="MerchantId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="MerchantId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="MerchantId" />
                        <span asp-validation-for="MerchantId"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Secret_OverrideForStore" asp-input="Secret" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Secret" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Secret" />
                        <span asp-validation-for="Secret"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AutoSettle_OverrideForStore" asp-input="AutoSettle" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AutoSettle" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AutoSettle" />
                        <span asp-validation-for="AutoSettle"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="HppVersion_OverrideForStore" asp-input="HppVersion" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="HppVersion" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="HppVersion" />
                        <span asp-validation-for="HppVersion"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="HppLanguageCode_OverrideForStore" asp-input="HppLanguageCode" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="HppLanguageCode" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="HppLanguageCode" />
                        <span asp-validation-for="HppLanguageCode"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="DefaultCurrencyCode_OverrideForStore" asp-input="DefaultCurrencyCode" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="DefaultCurrencyCode" />
                    </div>
                    <div class="col-md-9">
                        <select asp-for="DefaultCurrencyCode" asp-items="Model.DefaultCurrencySelectList" class="form-control"></select>
                        <span asp-validation-for="DefaultCurrencyCode"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UseCustomerCurrency_OverrideForStore" asp-input="UseCustomerCurrency" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UseCustomerCurrency" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseCustomerCurrency" />
                        <span asp-validation-for="UseCustomerCurrency"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn bg-primary" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Plugins/Nop.Plugin.Ecorenew.ElavonHppPayment/Views/EcorenewElavonHppPayment/ElavonHpp.cshtml
@model Nop.Plugin.Ecorenew.ElavonHppPayment.Domain.EcorenewElavonHppTransactionRequest
@{
    Layout = "~/Views/Shared/_ColumnsOne.cshtml";
    Html.AddCssFileParts(ResourceLocation.Head, "~/Plugins/Ecorenew.ElavonHppPayment/Content/css/hpp-payment.css");
    Html.AddScriptParts(ResourceLocation.Footer, "~/Plugins/Ecorenew.ElavonHppPayment/Scripts/hpp-payment.js");
}

<form id="ecorenew-elavon-hpp-form" method="POST" action="@ViewBag.EcorenewElavonHppRequestUrl" target="ecorenew_elavon_hpp_payment_iframe">
    <input type="hidden" name="TIMESTAMP" value="@Model.TIMESTAMP">
    <input type="hidden" name="MERCHANT_ID" value="@Model.MERCHANT_ID">
    <input type="hidden" name="ORDER_ID" value="@Model.ORDER_ID">
    <input type="hidden" name="AMOUNT" value="@Model.AMOUNT">
    <input type="hidden" name="CURRENCY" value="@Model.CURRENCY">
    <input type="hidden" name="SHA1HASH" value="@Model.SHA1HASH">
    <input type="hidden" name="AUTO_SETTLE_FLAG" value="@(Model.AUTO_SETTLE_FLAG ? "1" : "0")">

    @if (!string.IsNullOrWhiteSpace(Model.ACCOUNT))
    {
        <input type="hidden" name="ACCOUNT" value="@Model.ACCOUNT">
    }

    @if (!string.IsNullOrWhiteSpace(Model.COMMENT1))
    {
        <input type="hidden" name="COMMENT1" value="@Model.COMMENT1">
    }

    @if (!string.IsNullOrWhiteSpace(Model.COMMENT2))
    {
        <input type="hidden" name="COMMENT2" value="@Model.COMMENT2">
    }

    @if (!string.IsNullOrWhiteSpace(Model.SHIPPING_CODE))
    {
        <input type="hidden" name="SHIPPING_CODE" value="@Model.SHIPPING_CODE">
    }

    @if (!string.IsNullOrWhiteSpace(Model.SHIPPING_CO))
    {
        <input type="hidden" name="SHIPPING_CO" value="@Model.SHIPPING_CO">
    }

    @if (!string.IsNullOrWhiteSpace(Model.BILLING_CODE))
    {
        <input type="hidden" name="BILLING_CODE" value="@Model.BILLING_CODE">
    }

    @if (!string.IsNullOrWhiteSpace(Model.BILLING_CO))
    {
        <input type="hidden" name="BILLING_CO" value="@Model.BILLING_CO">
    }

    @if (!string.IsNullOrWhiteSpace(Model.CUST_NUM))
    {
        <input type="hidden" name="CUST_NUM" value="@Model.CUST_NUM">
    }

    @if (!string.IsNullOrWhiteSpace(Model.VAR_REF))
    {
        <input type="hidden" name="VAR_REF" value="@Model.VAR_REF">
    }

    @if (!string.IsNullOrWhiteSpace(Model.PROD_ID))
    {
        <input type="hidden" name="PROD_ID" value="@Model.PROD_ID">
    }

    @if (!string.IsNullOrWhiteSpace(Model.HPP_LANG))
    {
        <input type="hidden" name="HPP_LANG" value="@Model.HPP_LANG">
    }

    @if (!string.IsNullOrWhiteSpace(Model.HPP_VERSION))
    {
        <input type="hidden" name="HPP_VERSION" value="@Model.HPP_VERSION">
    }

    @if (!string.IsNullOrWhiteSpace(Model.MERCHANT_RESPONSE_URL))
    {
        <input type="hidden" name="MERCHANT_RESPONSE_URL" value="@Model.MERCHANT_RESPONSE_URL">
    }

    @if (!string.IsNullOrWhiteSpace(Model.CARD_PAYMENT_BUTTON))
    {
        <input type="hidden" name="CARD_PAYMENT_BUTTON" value="@Model.CARD_PAYMENT_BUTTON">
    }

    @if (!string.IsNullOrWhiteSpace(Model.SUPPLEMENTARY_DATA))
    {
        <input type="hidden" name="SUPPLEMENTARY_DATA" value="@Model.SUPPLEMENTARY_DATA">
    }
</form>

<iframe id="ecorenew-hpp-payment-iframe" name="ecorenew_elavon_hpp_payment_iframe" frameborder="0"></iframe>

Plugins/Nop.Plugin.Ecorenew.ElavonHppPayment/Views/EcorenewElavonHppPayment/ElavonHppResponseError.cshtml
<span id="ecorenew-elavon-hpp-error-message">
    @T("Ecorenew.ElavonHppPayment.HppErrorMessage")
</span>

Plugins/Nop.Plugin.Ecorenew.ElavonHppPayment/Views/EcorenewElavonHppPayment/PaymentInfo.cshtml
@{
    Layout = "";
}
<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <b>@T("Ecorenew.ElavonHppPayment.Fields.RedirectionTip")</b>
        </td>
    </tr>
</table>