Plugins/Nop.Plugin.Ecorenew.CustomOrderProcessing/Models/ConfigurationModel.cs
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Ecorenew.CustomOrderProcessing.Models
{
    public class ConfigurationModel
    {
        public int ActiveStoreScopeConfiguration { get; set; }

        [NopResourceDisplayName("Plugins.Ecorenew.CustomExportManager.Fields.CustomExportManagerEnabled")]
        public bool CustomOrderProcessingEnabled { get; set; }
        public bool CustomOrderProcessingEnabled_OverrideForStore { get; set; }
    }
}

Plugins/Nop.Plugin.Ecorenew.CustomOrderProcessing/Controllers/CustomOrderProcessingController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Plugin.Ecorenew.CustomOrderProcessing.Models;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Ecorenew.CustomOrderProcessing.Controllers
{
    public class CustomOrderProcessingController : BasePluginController
    {
        #region Fields

        private readonly ILocalizationService _localizationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IStoreService _storeService;
        private readonly IWorkContext _workContext;

        #endregion

        #region Ctor

        public CustomOrderProcessingController(ILocalizationService localizationService,
            IPermissionService permissionService,
            ISettingService settingService,
            IStoreService storeService,
            IWorkContext workContext)
        {
            this._localizationService = localizationService;
            this._permissionService = permissionService;
            this._settingService = settingService;
            this._storeService = storeService;
            this._workContext = workContext;
        }

        #endregion

        #region Methods

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageMessageTemplates))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = this.GetActiveStoreScopeConfiguration(_storeService, _workContext);
            var customOrderProcessingSettings = _settingService.LoadSetting<CustomOrderProcessingSettings>(storeScope);

            var model = new ConfigurationModel
            {
                ActiveStoreScopeConfiguration = storeScope,
                CustomOrderProcessingEnabled = customOrderProcessingSettings.CustomOrderProcessingEnabled
            };

            if (storeScope > 0)
            {
                model.CustomOrderProcessingEnabled_OverrideForStore = _settingService.SettingExists(customOrderProcessingSettings, x => x.CustomOrderProcessingEnabled, storeScope);
            }

            return View("~/Plugins/Ecorenew.CustomOrderProcessing/Views/Configure.cshtml", model);
        }

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        [HttpPost]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageMessageTemplates))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return Configure();

            // load settings for a chosen store scope
            var storeScope = this.GetActiveStoreScopeConfiguration(_storeService, _workContext);
            var customOrderProcessingSettings = _settingService.LoadSetting<CustomOrderProcessingSettings>(storeScope);

            customOrderProcessingSettings.CustomOrderProcessingEnabled = model.CustomOrderProcessingEnabled;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */
            _settingService.SaveSettingOverridablePerStore(customOrderProcessingSettings, x => x.CustomOrderProcessingEnabled, model.CustomOrderProcessingEnabled_OverrideForStore, storeScope, false);

            //now clear settings cache
            _settingService.ClearCache();

            SuccessNotification(_localizationService.GetResource("Admin.Plugins.Saved"));

            return Configure();
        }

        #endregion
    }
}

Plugins/Nop.Plugin.Ecorenew.CustomOrderProcessing/Views/Configure.cshtml
@{
    Layout = "_ConfigurePlugin";
}

@model ConfigurationModel
@using Nop.Plugin.Ecorenew.CustomOrderProcessing.Models;

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="CustomOrderProcessing" asp-action="Configure" method="post">
    <div class="content-header clearfix">
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
        </div>
    </div>

    <div asp-validation-summary="All"></div>

    <div class="content">
        <div class="form-horizontal">
            <nop-tabs id="custom-message-template-edit">
                <nop-tab asp-name="tab-custom-order-processing-event" asp-title="@T("Plugins.Ecorenew.CustomOrderProcessing.Title")" asp-default="true">@await Html.PartialAsync("~/Plugins/Ecorenew.CustomOrderProcessing/Views/_Configure.CustomOrderProcessing.cshtml", Model)</nop-tab>
            </nop-tabs>
        </div>
    </div>
</form>

Plugins/Nop.Plugin.Ecorenew.CustomOrderProcessing/Views/_Configure.CustomOrderProcessing.cshtml
@model ConfigurationModel
@using Nop.Plugin.Ecorenew.CustomOrderProcessing.Models;

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="form-group">
                <div class="col-md-3">
                    <nop-override-store-checkbox asp-for="CustomOrderProcessingEnabled_OverrideForStore" asp-input="CustomOrderProcessingEnabled" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                    <nop-label asp-for="CustomOrderProcessingEnabled" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="CustomOrderProcessingEnabled" />
                    <span asp-validation-for="CustomOrderProcessingEnabled"></span>
                </div>
            </div>
        </div>
    </div>
</div>