Presentation/Nop.Web/Areas/Admin/Controllers/ProductInsuranceSettingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core;
using Nop.Core.Domain.Configuration;
using Nop.Services;
using Nop.Services.Catalog;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Models.Settings;
using Nop.Web.Framework.Extensions;
using Nop.Web.Framework.Kendoui;
using Nop.Web.Framework.Mvc.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class ProductInsuranceSettingController : BaseAdminController
    {
        #region Fields
        private readonly IProductService _productService;
        private readonly IProductInsuranceSettingService _productInsuranceSettingService;
        private readonly IPermissionService _permissionService;
        private readonly IStoreContext _storeContext;
        private readonly ILocalizationService _localizationService;
        private readonly ICustomerActivityService _customerActivityService;
        #endregion

        #region Ctor
        public ProductInsuranceSettingController(IProductInsuranceSettingService productInsuranceSettingService,
            IPermissionService permissionService,
            IStoreContext storeContext,
            ILocalizationService localizationService,
            ICustomerActivityService customerActivityService, IProductService productService)
        {
            this._productService = productService;
            this._customerActivityService = customerActivityService;
            this._localizationService = localizationService;
            this._storeContext = storeContext;
            this._permissionService = permissionService;
            this._productInsuranceSettingService = productInsuranceSettingService;
        }
        #endregion
        #region Until


        protected virtual void PrepareProductInsuranceSettingModel(ProductInsuranceSettingModel model, ProductInsuranceSetting productInsuranceSetting)
        {
            if (productInsuranceSetting != null)
            {
                model.Id = productInsuranceSetting.Id;
                model.ProductType = productInsuranceSetting.ProductType;
                model.ProductInsuranceType = productInsuranceSetting.ProductInsuranceType.ToString();
                model.ProductId = productInsuranceSetting.ProductId;
                model.RangeEnd = productInsuranceSetting.RangeEnd;
                model.RangeStart = productInsuranceSetting.RangeStart;
                model.IsActive = productInsuranceSetting.IsActive;
            }

            var products = _productService.GetAllInsuranceProducts();
            model.AvailableProduct.Add(new SelectListItem { Text = _localizationService.GetResource("Admin.Configuration.SelectProductInsurance"), Value = "0" });
            if (products.Any())
            {
                foreach (var p in products)
                {
                    model.AvailableProduct.Add(new SelectListItem { Text = p.Name, Value = p.Id.ToString() });
                }
            }
        }
        #endregion

        #region Methods      
        //list
        public virtual IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageProductInsuranceSetting))
                return AccessDeniedView();
            var model = new ProductInsuranceSettingListModel()
            {
                AvailableProductType = ProductInsuranceType.AllProduct.ToSelectList(false).ToList()
            };
            //model.AvailableProductType.Insert(0, new SelectListItem
            //{ Text = _localizationService.GetResource("Admin.Common.All"), Value = "0", Selected = true });
            return View(model);
        }

        [HttpPost]
        public virtual IActionResult List(ProductInsuranceSettingListModel model, DataSourceRequest command)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageProductInsuranceSetting))
                return AccessDeniedView();

            var productInsuranceSettings = _productInsuranceSettingService.GetAllProductInsuranceSetting(
                productType:model.ProductType,
                pageIndex: command.Page - 1,
                pageSize: command.PageSize
                );
            var gridModel = new DataSourceResult
            {
                Data = productInsuranceSettings.PagedForCommand(command).Select(x =>
                {
                    return new ProductInsuranceSettingModel
                    {
                        Id = x.Id,
                        ProductId = x.ProductId,
                        ProductType = x.ProductType,
                        ProductInsuranceType = x.ProductInsuranceType.ToString(),
                        RangeEnd = x.RangeEnd,
                        RangeStart = x.RangeStart,
                        ProductName = x.Product?.Name,
                        ProductPrice=x.Product?.Price,
                        IsActive = x.IsActive,
                    };
                }),
                Total = productInsuranceSettings.Count,
            };
            return Json(gridModel);
        }

        //create 
        public virtual IActionResult Create()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageProductInsuranceSetting))
                return AccessDeniedView();
            var model = new ProductInsuranceSettingModel();
            PrepareProductInsuranceSettingModel(model, null);
            model.IsActive = true;
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult Create(ProductInsuranceSettingModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageProductInsuranceSetting))
                return AccessDeniedView();
            var product = _productService.GetProductById(model.ProductId);
            if (product == null)
            {
                ModelState.AddModelError("", "Please select Product!");
            }
            if (ModelState.IsValid)
            {
                var productInsuranceSetting = new ProductInsuranceSetting
                {
                    ProductId = model.ProductId,
                    IsActive = model.IsActive,
                    RangeEnd = model.RangeEnd,
                    RangeStart = model.RangeStart,
                    ProductType = model.ProductType,
                };
                _productInsuranceSettingService.InsertProductInsuranceSetting(productInsuranceSetting);

                SuccessNotification(_localizationService.GetResource("Admin.Configuration.ProductInsuranceSetting.Added"));
                if (continueEditing)
                {
                    //selected tab
                    SaveSelectedTabName();
                    return RedirectToAction("Edit", new { id = productInsuranceSetting.Id });
                }
                return RedirectToAction("List");
            }
            //If we got this far, something failed, redisplay form
            PrepareProductInsuranceSettingModel(model, null);
            return View(model);
        }

        //edit
        public virtual IActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageProductInsuranceSetting))
                return AccessDeniedView();

            var productInsuranceSetting = _productInsuranceSettingService.GetProductInsuranceSettingById(id);
            if (productInsuranceSetting == null)
                //No productInsuranceSetting  found with the specified id
                return RedirectToAction("List");

            var model = new ProductInsuranceSettingModel();
            PrepareProductInsuranceSettingModel(model, productInsuranceSetting);
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult Edit(ProductInsuranceSettingModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageProductInsuranceSetting))
                return AccessDeniedView();

            var productInsuranceSetting = _productInsuranceSettingService.GetProductInsuranceSettingById(model.Id);
            if (productInsuranceSetting == null)
                //No productInsuranceSetting found with the specified id
                return RedirectToAction("List");
            var product = _productService.GetProductById(model.ProductId);
            if (product == null)
            {
                ModelState.AddModelError("", "Please select Product!");
            }
            if (ModelState.IsValid)
            {
                
                productInsuranceSetting.IsActive = model.IsActive;
                productInsuranceSetting.ProductId = model.ProductId;
                productInsuranceSetting.RangeEnd = model.RangeEnd;
                productInsuranceSetting.RangeStart = model.RangeStart;
                productInsuranceSetting.ProductType = model.ProductType;
                _productInsuranceSettingService.UpdateProductInsuranceSetting(productInsuranceSetting);


                SuccessNotification(_localizationService.GetResource("Admin.Configuration.ProductInsuranceSetting.Updated"));

                if (continueEditing)
                {
                    //selected tab
                    SaveSelectedTabName();

                    return RedirectToAction("Edit", new { id = productInsuranceSetting.Id });
                }
                return RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form

Presentation/Nop.Web/Areas/Admin/Views/ProductInsuranceSetting/Create.cshtml
@model ProductInsuranceSettingModel
@using Nop.Web.Areas.Admin.Models.Settings

@{
    //page title
    ViewBag.Title = T("Admin.Configuration.ProductInsuranceSetting.AddNew").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Product Insurance Setting");

<form asp-controller="ProductInsuranceSetting" asp-action="Create" method="post" id="productInsuranceSetting-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Configuration.ProductInsuranceSetting.AddNew")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Configuration.ProductInsuranceSetting.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
}

Presentation/Nop.Web/Areas/Admin/Views/ProductInsuranceSetting/Edit.cshtml
@model ProductInsuranceSettingModel
@using Nop.Web.Areas.Admin.Models.Settings

@{
    //page title
    ViewBag.Title = T("Admin.Configuration.ProductInsuranceSetting.EditBankInfoDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Product Insurance Setting");
}

<form asp-controller="ProductInsuranceSetting" asp-action="Edit" method="post" id="productInsuranceSetting-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Configuration.ProductInsuranceSetting.EditBankInfoDetails") - @Model.Id
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Configuration.ProductInsuranceSetting.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="productInsuranceSetting-info-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="productInsuranceSetting-delete" />

Presentation/Nop.Web/Areas/Admin/Views/ProductInsuranceSetting/List.cshtml
@model ProductInsuranceSettingListModel
@using Nop.Web.Areas.Admin.Models.Settings
@inject AdminAreaSettings adminAreaSetting
@{
    var defaultGridPageSize = adminAreaSetting.DefaultGridPageSize;
    var gridPageSizes = adminAreaSetting.GridPageSizes;

    //page title
    ViewBag.Title = T("Admin.Configuration.ProductInsuranceSetting").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Product Insurance Setting");
}
<nop-antiforgery-token />
<div class="content-header clearfix">
    <h1 class="pull-left">
        @T("Admin.Configuration.ProductInsuranceSetting")
    </h1>
    <div class="pull-right">
        <a asp-action="Create" class="btn bg-blue">
            <i class="fa fa-plus-square"></i>
            @T("Admin.Common.AddNew")
        </a>
    </div>
</div>
<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default panel-search">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                    <nop-label asp-for="ProductType" />
                                </div>
                                <div class="col-md-8">
                                    <nop-select asp-for="ProductType" asp-items="Model.AvailableProductType" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="button" id="search-productInsuranceSetting-record" class="btn btn-primary btn-search">
                                        <i class="fa fa-search"></i>
                                        @T("Admin.Common.Search")
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-body">
                    <div id="productInsuranceSetting-record-grid"></div>
                    <script type="text/javascript">
                        $(function(){
                            $("#productInsuranceSetting-record-grid").kendoGrid({
                                dataSource: {
                                    type: 'json',
                                    transport: {
                                        read: {
                                            url: "@Html.Raw(Url.Action("List", "ProductInsuranceSetting"))",
                                            type: "POST",
                                            dataType: "json",
                                            data: additionalData
                                        },
                                    },
                                    schema: {
                                        data: "Data",
                                        total: "Total",
                                        errors:"Errors"
                                    },
                                    error: function (e) {
                                        display_kendoui_grid_error(e);
                                        this.cancelChanges();
                                    },
                                    pageSize: @(defaultGridPageSize),
                                    serverPaging: true,
                                    serverFiltering: true,
                                    serverSorting: true
                                },
                                //分页
                                 pageable: {
                                    refresh: true,
                                    pageSizes: [@(gridPageSizes)],
                                    @await Html.PartialAsync("_GridPagerMessages")
                                },
                                editable: {
                                    confirmation: "@T("Admin.Common.DeleteConfirmation")",
                                    mode: "inline"
                                },
                                scrollable: false,
                                columns: [
                                    {
                                        field: "ProductInsuranceType",
                                        title: "@T("Admin.Configuration.ProductInsuranceSetting.Fields.ProductType")",
                                        template: '<span class="grid-report-item ' +
                                            '# if(ProductType == 232) {# yellow #} #' +
                                            '# if(ProductType == 203) {# blue #} #' +
                                            '">#=ProductInsuranceType#</span>'
                                    },{
                                        field: "ProductId",
                                        title: "@T("Admin.Configuration.ProductInsuranceSetting.Fields.ProductId")",
                                    },{
                                        field: "ProductName",
                                        title: "@T("Admin.Configuration.ProductInsuranceSetting.Fields.ProductName")",
                                        template:'<em><a href="/Admin/Product/Edit/#=ProductId#">#=ProductName#</a></em>',
                                    },{
                                        field: "ProductPrice",
                                        title: "@T("Admin.Configuration.ProductInsuranceSetting.Fields.ProductPrice")",
                                    },{
                                        field: "RangeStart",
                                        title: "@T("Admin.Configuration.ProductInsuranceSetting.Fields.RangeStart")",
                                    },{
                                        field: "RangeEnd",
                                        title: "@T("Admin.Configuration.ProductInsuranceSetting.Fields.RangeEnd")",
                                    },{
                                        field: "IsActive",
                                        title: "@T("Admin.Configuration.ProductInsuranceSetting.Fields.IsActive")",
                                        template: '# if(IsActive) {# <i class="fa fa-check true-icon"></i> #} else {# <i class="fa fa-close false-icon"></i> #} #'
                                    },{
                                        field: "Id",
                                        title: "@T("Admin.Common.Edit")",
                                        headerAttributes: { style: "text-align:cneter" },
                                        attributes: { style: "text-align:center" },
                                        template:'<a class="btn btn-default" href="Edit/#=Id#"><i class="fa fa-pencil"></i>@T("Admin.Common.Edit")</a>'
                                    },
                                ],
                            });
                        });
                    </script>
                    <script type="text/javascript">
                        $(function () {
                            $("#search-productInsuranceSetting-record").click(function () {
                                var grid = $("#productInsuranceSetting-record-grid").data('kendoGrid');
                                grid.dataSource.page(1);
                                return false;
                            });
                        });
                        function additionalData() {
                              var data = {
                               ProductType: $('#@Html.IdFor(model => model.ProductType)').val(),
                            }
                            addAntiForgeryToken(data);
                            return data;
                        }
                    </script>
                </div>
            </div>

        </div>
    </div>
</div>

Presentation/Nop.Web/Areas/Admin/Views/ProductInsuranceSetting/_CreateOrUpdate.Info.cshtml
@model ProductInsuranceSettingModel
@using Nop.Core.Domain.Configuration
@using Nop.Web.Areas.Admin.Models.Settings
@using Nop.Services

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="ProductId" />
                </div>
                <div class="col-md-9">
                    <nop-select asp-for="ProductId" asp-items="Model.AvailableProduct" />
                    <span asp-validation-for="ProductId"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="ProductType" />
                </div>
                <div class="col-md-9">
                    <nop-select asp-for="ProductType" asp-items="@(((ProductInsuranceType)Model.ProductType).ToSelectList())" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="RangeStart" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="RangeStart" />
                    <span asp-validation-for="RangeStart"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="RangeEnd" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="RangeEnd" />
                    <span asp-validation-for="RangeEnd"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="IsActive" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="IsActive" />
                    <span asp-validation-for="IsActive"></span>
                </div>
            </div>
        </div>
    </div>
</div>

Presentation/Nop.Web/Areas/Admin/Views/ProductInsuranceSetting/_CreateOrUpdate.cshtml
@model ProductInsuranceSettingModel
@using Nop.Web.Areas.Admin.Models.Settings
@inject IEventPublisher eventPublisher

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

<div class="content">
    <div class="form-horizontal">
        <nop-tabs id="bank-info-edit">
            <nop-tab asp-name="tab-info" asp-title="@T("Admin.Configuration.ProductInsuranceSetting.Info")" asp-default="true">@await Html.PartialAsync("_CreateOrUpdate.Info", Model)</nop-tab>
        </nop-tabs>
    </div>
</div>

@{
    //custom tabs
    var eventMessage = new AdminTabStripCreated(this.Html, "ProductInsuranceSetting-info-edit");
    eventPublisher.Publish(eventMessage);
    foreach (var eventBlock in eventMessage.BlocksToRender)
    {
        @eventBlock
    }
}